// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:7e6a6aa5-ba3b-4765-ae57-a8fa548560bf",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_lEqUK8mlY",
    "aws_user_pools_web_client_id": "3fdhg970h6cc1vsnismjstbmv5",
    "oauth": {},
    "aws_user_files_s3_bucket": "files-consulta194533-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
